### ISSUE TITLE
Not really works with development mode

### ISSUE THREAD

**Issue by snapshotpl** [zendframework/zend-component-installer#10]
I have installed fresh skeleton. After this I enabled development mode:

```
composer zf-development-mode
```

and required developer tools

```
composer require --dev zendframework/zend-developer-tools
```

Component installer gave mi 3 options:

```
Please select which config file you wish to inject 'ZendDeveloperTools' into:
  [0] Do not inject
  [1] config/modules.config.php
  [2] config/development.config.php.dist
```

Hovewer there's no option to attach module to current `development.config.php`. After choose `2` option I  needed to disable and enable again development mode to make developer tools working.

**Comment by weierophinney** [comment]
This is actually correct.

`config/development.config.php` is excluded from the repository with the `.gitignore` rules we supply, while `config/development.config.php.dist` can and should be checked in. Whenever you enable development mode, it copies `development.config.php.dist` to `development.config.php` — which means that the `.dist` file is the canonical version.

As such, always perform edits on the `.dist` file, and then disable/enable to apply them. You should never edit the `development.config.php` file itself.

**Comment by snapshotpl** [comment]
@weierophinney are you sure it's correct? Why not to edit `config/development.config.php.dist` and `config/development.config.php` if exists? I known where to search this and I quickly fixed that, but for newbies will be hard step

**Comment by weierophinney** [comment]
@snapshotpl Here's a compromise: have it install to `development.config.php.dist`, but if a `development.config.php` is found, emit a message along the lines of

``` text
You will need to disable and then enable development mode after installation completes for the changes to take effect.
```

Thoughts?
