### ISSUE TITLE
Deprecation Notice on every ZF module install

### ISSUE THREAD

**Issue by ikovalyov** [zendframework/zend-component-installer#28]
Deprecation Notice: The callback Zend\ComponentInstaller\ComponentInstaller::onPostPackageInstall declared at /home/runner/cdnperf.com/vendor/zendframework/zend-component-installer/src/ComponentInstaller.php accepts a Composer\Script\PackageEvent but post-package-install events use a Composer\Installer\PackageEvent instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///home/runner/.phpbrew/php/php-7.0.13/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:308

**Comment by michalbundyra** [comment]
@ikovalyov Please see my hotfix #29

**Comment by seyfer** [comment]
I which version of component installer it fixed?

Still have this issue with this config:
`zendframework/zend-component-installer: ^1.0 || ^0.3 || ^1.0.0-dev@dev`

**Comment by weierophinney** [comment]
Version 0.5.1. It should be BC for consumers, so you can update the 0.3 constraint to 0.5.

**Comment by seyfer** [comment]
@weierophinney, I will try, thank you.

I'm using these versions because the are the same in current SkeletonApplication
https://github.com/zendframework/ZendSkeletonApplication/blob/master/composer.json
