### ISSUE TITLE
Migration from Zend\Expressive\ConfigManager to Zend\ConfigAggregator

### ISSUE THREAD

**Issue by gabbydgab** [zendframework/zend-component-installer#30]
## **Small change but backwards incompatible**

Replacing [mtymek/expressive-config-manager](https://github.com/mtymek/expressive-config-manager) with [zend-config-aggregator](https://github.com/zendframework/zend-config-aggregator) will cause bc breaks with existing applications consuming this package due to its (official) NAMESPACE (Zend\ConfigAggregator) - even though they are almost identical library.

Following change would be:

```php
Zend\Expressive\ConfigManager\ConfigManager::class => Zend\ConfigAggregator\ConfigAggregator::class
Zend\Expressive\ConfigManager\PhpFileProvider => Zend\ConfigAggregator\PhpFileProvider
```

### Why Zend\ConfigAggregator?
> While designed for Expressive applications, it can work with any PHP project for aggregating and returning merged configuration, from either a variety of configuration formats or "configuration providers", invokable classes returning an array of configuration (or a PHP generator). It also supports configuration caching.

See: https://github.com/zendframework/zend-config-aggregator

### What needs to be done?
 - Update the injection of config provider namespace in [ExpressiveConfigInjector](https://github.com/zendframework/zend-component-installer/blob/master/src/Injector/ExpressiveConfigInjector.php#L68-L78) and corresponding tests.
- Update the config provider discovery namespace in [ExpressiveConfig](https://github.com/zendframework/zend-component-installer/blob/master/src/ConfigDiscovery/ExpressiveConfig.php#L29-L32) and corresponding tests

 - Update [Document ](https://github.com/zendframework/zend-component-installer/blob/9b6b18afc4178a3b9437ee433317cb8695057d21/doc/book/index.html#L140)  explaining the changes - with the new NAMESPACE (Zend\ConfigAggregator) and migration instruction.

**Comment by weierophinney** [comment]
I'll update it to manage both, as that way those who are already using the original ConfigManager will still be able to use the functionality.

Thanks for creating the issue!
