### ISSUE TITLE
maybe time for 1.0 release? or there is a reason why not?

### ISSUE THREAD

**Issue by svycka** [zendframework/zend-component-installer#32]
It is a bit annoying to update it in composer. And for example even ZendSkeletonApplication uses outdated version (0.3.1 - 2016-09-12) https://github.com/zendframework/ZendSkeletonApplication/blob/release-3.0.1/composer.json#L16

**Comment by weierophinney** [comment]
There are a few reasons to wait.

First, we're still exploring what the feature-set should be. I just pushed 0.6.0, which adds support for the new zend-config-aggregator.

Second, there's likely a need for a significant refactor. When doing the changes for 0.6.0, I realized that separating discovery from injection actually leads to significant code duplication, and makes understanding the code flow more difficult. I'd like to simplify this if possible, but that will likely lead to rather large architectural changes.
