### ISSUE TITLE
[Question] Config Providers (aka Modules) Prioritization for Expressive Application

### ISSUE THREAD

**Issue by gabbydgab** [zendframework/zend-component-installer#33]
## Components VS Config Provider Prioritization
Does ConfigProviders (aka Modules) has the same priority with ZF2/3 Modules when it comes to injecting of dependencies in an Expressive application?

I was experimenting on my dependencies and upon observation, the zend-components (like zend-navigation, zend-validator, etc) are appended after my Config Providers (aka Modules).

```php
$config = new ConfigAggregator(
    [
        \MyNamespace\WebHelper\ConfigProvider::class,
        \MyNamespace\ErrorHandler\ConfigProvider::class,
        \Zend\Router\ConfigProvider::class,
        \Zend\Validator\ConfigProvider::class,
        \Zend\Navigation\ConfigProvider::class,
        new PhpFileProvider('config/autoload/{{,*.}global,{,*.}local}.php'),
        new PhpFileProvider('config/development.config.php')
    ],
    __DIR__ . '/../data/cache/application.config.php'
);
```
## Multiple Config Provider Prioritization
Since there is no priority settings in the configuration, I'm creating a separate metapackage (similar to [zend-mvc-plugins](https://github.com/zendframework/zend-mvc-plugins/blob/master/composer.json)) expecting that the order of the config providers should be maintained upon injection

If having this metapackage configuration:
```json
"extra": {
        "zf": {
      	    "config-provider": [
                "MyNamespace\ExpressiveErrorHandler\ConfigProvider",
                "MyNamespace\ExpressiveWebHelper\ConfigProvider"
            ]
        }
    }
```

**_Expectation:_** 
```php
$config = new ConfigAggregator(
    [
        \MyNamespace\ErrorHandler\ConfigProvider::class,
        \MyNamespace\WebHelper\ConfigProvider::class,
        new PhpFileProvider('config/autoload/{{,*.}global,{,*.}local}.php'),
        new PhpFileProvider('config/development.config.php')
    ],
    __DIR__ . '/../data/cache/application.config.php'
);
```

**_Actual Result_**
It seems the prioritization is based on composers ability to pull packages. If the package has no (lesser) dependencies then the package will be injected (asked) first. But assuming that these packages are available, should the configuration be maintained?

@webimpress @weierophinney 
This may be an enhancement but I love to know your points about this matter. Thanks in advance.

Related Issue/PR: https://github.com/zendframework/zend-component-installer/pull/16

**Comment by weierophinney** [comment]
Packages are injected in the order in which composer installs them; the plugin is run on successful completion of each package. Since composer generally will install dependencies first, the actual result you note above is expected.
