### ISSUE TITLE
Documentation folder is named `docs` instead of `doc`

### ISSUE THREAD

**Issue by dluciv** [zendframework/zend-component-installer#45]
Which, among all, causes https://docs.zendframework.com/zend-component-installer/ to miss documentation

**Comment by froschdesign** [comment]
@dluciv 
> `docs` instead of `doc`

The folder name is correct! See `mkdocs.yml`:

https://github.com/zendframework/zend-component-installer/blob/ba635fff465399e4ba8fdbee237471858fd30f99/mkdocs.yml#L1-L2

At the moment, the documentation for this component has only one page - the home page.
